image:
  repository: ghcr.io/ekorsa/fastapi_docker_test
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: ghcr-secret

nameOverride: ""
fullnameOverride: ""

replicaCount: 2

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  annotations: {}

  hosts:
    app: my-app.local
    grafana: grafana.local

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

